"""Generate the synthetic fixture, fit a clean baseline, score, and write the measured result.

Usage (from this directory):
    python run_fixture.py

Exit code is 0 only when every scripted class outranks every holdout-clean player.
A high-skill human may still outrank a recoil script on the composite. That is
recorded, not hidden: the queue is not a ban list.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def _run(script: str, args: list[str]) -> None:
    cmd = [sys.executable, str(Path(__file__).with_name(script)), *args]
    subprocess.check_call(cmd, cwd=Path(__file__).parent)


def _table(frame: pd.DataFrame) -> str:
    show = frame.copy()
    for col in show.columns:
        if pd.api.types.is_float_dtype(show[col]):
            show[col] = show[col].map(lambda v: "" if pd.isna(v) else f"{v:.3f}")
    header = " | ".join(str(c) for c in show.columns)
    rule = " | ".join("---" for _ in show.columns)
    body = [" | ".join("" if pd.isna(v) else str(v) for v in row) for row in show.itertuples(index=False, name=None)]
    return "\n".join([header, rule, *body])


def main() -> int:
    _run("generate_fixture.py", [])
    _run(
        "baseline.py",
        ["--samples", str(DATA / "clean_samples.csv"), "--out", str(DATA / "baseline.json"), "--min-players", "10"],
    )
    _run(
        "detectors.py",
        [
            "--samples",
            str(DATA / "match_samples.csv"),
            "--baseline",
            str(DATA / "baseline.json"),
            "--out",
            str(DATA / "scores.csv"),
            "--min-matches",
            "2",
        ],
    )

    scores = pd.read_csv(DATA / "scores.csv")
    labels = pd.read_csv(DATA / "labels.csv")
    merged = scores.merge(labels, on="player_id", how="left")
    merged = merged.sort_values("score", ascending=False)

    summary = (
        merged.groupby("label")["score"]
        .agg(["count", "median", "min", "max"])
        .round(3)
        .reset_index()
    )
    holdout_max = float(merged.loc[merged["label"] == "holdout_clean", "score"].max())
    scripted = merged["label"].isin(["snap_aim", "triggerbot", "recoil_script"])
    scripted_min = float(merged.loc[scripted, "score"].min())
    separated = scripted_min > holdout_max
    skilled = merged.loc[merged["label"] == "high_skill_human", "score"]
    skilled_max = float(skilled.max()) if not skilled.empty else float("nan")
    overlap = skilled_max > scripted_min

    queue = merged[["player_id", "label", "score", "features_used", "top_features"]].head(15)
    lines = [
        "# Fixture results",
        "",
        "Synthetic data only. Generated by `detections/run_fixture.py`. These numbers are the output of this repo's scorer, not a claim about any live game.",
        "",
        f"Separation check: scripted minimum score {scripted_min:.3f} vs holdout-clean maximum {holdout_max:.3f}.",
        f"Scripted classes outrank every holdout-clean player: **{separated}**.",
        f"High-skill maximum {skilled_max:.3f} sits above the lowest recoil script {scripted_min:.3f}: **{overlap}**.",
        "Sorting the composite and cutting a line would queue that human before the script. The script is identifiable because recoil_regularity and recoil_residual lead its feature list. The skilled player's top features are jerk, Fitts slope, and fire latency. Close the skilled player. Do not auto-ban either from the composite.",
        "",
        "## Score by label",
        "",
        _table(summary),
        "",
        "## Review queue (top 15)",
        "",
        _table(queue),
        "",
    ]
    DOCS.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines)
    (DOCS / "fixture-results.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {DOCS / 'fixture-results.md'}")
    return 0 if separated else 2


if __name__ == "__main__":
    raise SystemExit(main())
